config/routes.rb
Rails.application.routes.draw do
  resources :capsules
  get 'pages/home'

root 'pages#home'

end

app/models/capsule.rb
class Capsule < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/capsules_controller.rb
class CapsulesController < ApplicationController
  before_action :set_capsule, only: [:show, :edit, :update, :destroy]

  # GET /capsules
  # GET /capsules.json
  def index
    @capsules = Capsule.all
  end

  # GET /capsules/1
  # GET /capsules/1.json
  def show
  end

  # GET /capsules/new
  def new
    @capsule = Capsule.new
  end

  # GET /capsules/1/edit
  def edit
  end

  # POST /capsules
  # POST /capsules.json
  def create
    @capsule = Capsule.new(capsule_params)

    respond_to do |format|
      if @capsule.save
        format.html { redirect_to @capsule, notice: 'Capsule was successfully created.' }
        format.json { render :show, status: :created, location: @capsule }
      else
        format.html { render :new }
        format.json { render json: @capsule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /capsules/1
  # PATCH/PUT /capsules/1.json
  def update
    respond_to do |format|
      if @capsule.update(capsule_params)
        format.html { redirect_to @capsule, notice: 'Capsule was successfully updated.' }
        format.json { render :show, status: :ok, location: @capsule }
      else
        format.html { render :edit }
        format.json { render json: @capsule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /capsules/1
  # DELETE /capsules/1.json
  def destroy
    @capsule.destroy
    respond_to do |format|
      format.html { redirect_to capsules_url, notice: 'Capsule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_capsule
      @capsule = Capsule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def capsule_params
      params.require(:capsule).permit(:message, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capsules_helper.rb
module CapsulesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/capsules/_form.html.erb
<%= form_for(@capsule, :html => { multipart: true }) do |f| %>
  <% if @capsule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@capsule.errors.count, "error") %> prohibited this capsule from being saved:</h2>

      <ul>
      <% @capsule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :message %><br>
    <%= f.text_field :message, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/capsules/edit.html.erb
<h1>Editing Capsule</h1>

<%= render 'form' %>

<%= link_to 'Show', @capsule %> |
<%= link_to 'Back', capsules_path %>

app/views/capsules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Capsules</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @capsules.each do |capsule| %>
      <tr>
        <td><%= capsule.message %></td>
        <td><%= link_to 'Show', capsule %></td>
        <td><%= link_to 'Edit', edit_capsule_path(capsule) %></td>
        <td><%= link_to 'Destroy', capsule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Capsule', new_capsule_path %>

app/views/capsules/new.html.erb
<h1>New Capsule</h1>

<%= render 'form' %>

<%= link_to 'Back', capsules_path %>

app/views/capsules/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @capsule.image_url %>

<p>
  <strong>Message:</strong>
  <%= @capsule.message %>
</p>

<%= link_to 'Edit', edit_capsule_path(@capsule) %> |
<%= link_to 'Back', capsules_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eternity</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Project Eternity </h1>
<p>Find me in app/views/pages/home.html.erb</p>
<a href="/capsules">See our Capsules !</a>